site_name: IA en Educación Superior
site_url: https://sitename.example
repo_url: https://github.com/mjoviedo/test-mkdocs
repo_name: mjoviedo/test-mkdocs
edit_uri: edit/main/docs/
theme:
  name: material
  language: es
  icon:
    logo: fontawesome/solid/hexagon-nodes
    edit: fontawesome/solid/pen-to-square
  features:
    - navigation.footer
    - navigation.tabs
    - content.action.edit
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: fontawesome/solid/sun
        name: Modo oscuro
      primary: pink
      accent: teal

    # Light Mode
    - scheme: default
      toggle:
        icon: fontawesome/solid/moon
        name: Modo claro
      primary: teal
      accent: pink
    

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
       custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

nav:
  - Inicio:
    - Bienvenida: index.md
    - Acerca de: inicio/acercade.md
    - Comunidad: inicio/comunidad.md
  - Modulo 1:
    - Presentación: modulo1/intro.md


plugins:
  - git-committers:
      repository: squidfunk/mkdocs-material
      branch: main
      enabled: !ENV [CI, false]

extra:
  social:
    - icon: fontawesome/solid/graduation-cap
      link: https://eco.unc.edu.ar
    - icon: fontawesome/brands/discord
      link: https://discord.gg/tx4p2AZU
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/economicasunc/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/fceconomicas
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/school/economicasunc/
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@economicasunc
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/EconomicasUNC
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/EcoUNC/

copyright: FyPE - Facultad de Ciencias Económicas - Universidad Nacional de Córdoba

